stocks:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      keyfile: "/keys/dbt-dev-sa.json"
      project: "metal-lantern-344112"
      dataset: "dbt_dev"
      location: "europe-central2"
      priority: interactive
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 0
