name: 'Terraform GitHub Actions'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.TERRAFORM_GCP_SA_KEY }}

    - name: Write service account keyfile to runner filesystem
      run: mkdir caution && echo "${{ secrets.TERRAFORM_GCP_ZIP_CF_SA_KEY }}" | base64 -d > caution/terraform-cf-zip-sa-keyfile.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
